name: Build Fluentd Kubernetes Damonset Image

on:
  push:
    paths:
      - 'fluentd-es/kubernetes/arm64/debian-elasticsearch7/**'
  workflow_run:
    workflows: ["Build Fluentd Image"]
    types:
      - completed

env:
  DOCKER_REGISTRY: docker.io/liuxincuit/fluentd-kubernetes-daemonset
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push for arm64
        uses: docker/build-push-action@v6
        with:
          context: ./fluentd-es/kubernetes/arm64/debian-elasticsearch7/
          provenance: false
          push: true
          platforms: linux/arm64
          pull: true
          no-cache: true
          tags: ${{ env.DOCKER_REGISTRY }}:v1.15.3-debian-elasticsearch7-1.2
          # dare to use old mediatype (application/vnd.docker.distribution.manifest.v2+json)
          outputs: oci-mediatypes=false